// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v7.35.0
// source: proto/product.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ProductInventoryService_ReserveProduct_FullMethodName = "/pb.ProductInventoryService/ReserveProduct"
	ProductInventoryService_ReleaseProduct_FullMethodName = "/pb.ProductInventoryService/ReleaseProduct"
)

// ProductInventoryServiceClient is the client API for ProductInventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductInventoryServiceClient interface {
	ReserveProduct(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error)
	ReleaseProduct(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error)
}

type productInventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductInventoryServiceClient(cc grpc.ClientConnInterface) ProductInventoryServiceClient {
	return &productInventoryServiceClient{cc}
}

func (c *productInventoryServiceClient) ReserveProduct(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error) {
	out := new(ReserveResponse)
	err := c.cc.Invoke(ctx, ProductInventoryService_ReserveProduct_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productInventoryServiceClient) ReleaseProduct(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseResponse, error) {
	out := new(ReleaseResponse)
	err := c.cc.Invoke(ctx, ProductInventoryService_ReleaseProduct_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductInventoryServiceServer is the server API for ProductInventoryService service.
// All implementations must embed UnimplementedProductInventoryServiceServer
// for forward compatibility
type ProductInventoryServiceServer interface {
	ReserveProduct(context.Context, *ReserveRequest) (*ReserveResponse, error)
	ReleaseProduct(context.Context, *ReleaseRequest) (*ReleaseResponse, error)
	mustEmbedUnimplementedProductInventoryServiceServer()
}

// UnimplementedProductInventoryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProductInventoryServiceServer struct {
}

func (UnimplementedProductInventoryServiceServer) ReserveProduct(context.Context, *ReserveRequest) (*ReserveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReserveProduct not implemented")
}
func (UnimplementedProductInventoryServiceServer) ReleaseProduct(context.Context, *ReleaseRequest) (*ReleaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseProduct not implemented")
}
func (UnimplementedProductInventoryServiceServer) mustEmbedUnimplementedProductInventoryServiceServer() {
}

// UnsafeProductInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductInventoryServiceServer will
// result in compilation errors.
type UnsafeProductInventoryServiceServer interface {
	mustEmbedUnimplementedProductInventoryServiceServer()
}

func RegisterProductInventoryServiceServer(s grpc.ServiceRegistrar, srv ProductInventoryServiceServer) {
	s.RegisterService(&ProductInventoryService_ServiceDesc, srv)
}

func _ProductInventoryService_ReserveProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductInventoryServiceServer).ReserveProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductInventoryService_ReserveProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductInventoryServiceServer).ReserveProduct(ctx, req.(*ReserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductInventoryService_ReleaseProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductInventoryServiceServer).ReleaseProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductInventoryService_ReleaseProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductInventoryServiceServer).ReleaseProduct(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductInventoryService_ServiceDesc is the grpc.ServiceDesc for ProductInventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductInventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ProductInventoryService",
	HandlerType: (*ProductInventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReserveProduct",
			Handler:    _ProductInventoryService_ReserveProduct_Handler,
		},
		{
			MethodName: "ReleaseProduct",
			Handler:    _ProductInventoryService_ReleaseProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/product.proto",
}
