apiVersion: v1
kind: Namespace
metadata:
  name: omnigo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: omnigo-config
  namespace: omnigo
data:
  DATABASE_URL: "postgres://omnigo_user:omnigo_password@omnigo-postgres:5432/omnigo_db?sslmode=disable"
  DB_WRITER_DSN: "postgres://omnigo_user:omnigo_password@omnigo-postgres:5432/omnigo_db?sslmode=disable"
  DB_READER_DSN: "postgres://omnigo_user:omnigo_password@omnigo-postgres:5432/omnigo_db?sslmode=disable"
  REDIS_ADDRS: "omnigo-redis:6379"
  TIGERBEETLE_ADDRESSES: "omnigo-tigerbeetle:3000"
  TB_ENABLED: "true"
  KAFKA_BROKERS: "omnigo-kafka:9092"
  DEFAULT_CURRENCY: "PKR"
  ESCROW_HOLD_HOURS: "48"
  DEFAULT_COMMISSION_RATE: "2.0"
---
apiVersion: v1
kind: Secret
metadata:
  name: omnigo-secrets
  namespace: omnigo
type: Opaque
stringData:
  POSTGRES_USER: "omnigo_user"
  POSTGRES_PASSWORD: "omnigo_password"
  POSTGRES_DB: "omnigo_db"
  JWT_SECRET_KEY: "csiPLQIJqstuH6rIa6ulOdjl30RMYqwfk2cwTPoj2nAVHykMdWixUJnwVt6NovAyUDMqLoryPxQOSPM6jr6MlQ=="
  PAYFAST_MERCHANT_ID: "100000000000000"
  PAYFAST_SECURED_KEY: "your_secured_key"
  PAYFAST_BASE_URL: "https://ipg.gopayfast.com"
  INTERNAL_CALLBACK_SECRET: "internal-callback-secret-32-chars"
