apiVersion: v1
kind: Service
metadata:
  name: {{ include "omnigo.fullname" . }}-ai-engine
  labels:
    {{- include "omnigo.labels" . }}
spec:
  ports:
    - port: {{ .Values.services.aiEngine.port }}
      targetPort: 8088
  selector:
    app.kubernetes.io/name: {{ include "omnigo.name" . }}-ai-engine
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "omnigo.fullname" . }}-ai-engine
  labels:
    {{- include "omnigo.labels" . }}
spec:
  replicas: {{ .Values.services.aiEngine.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "omnigo.name" . }}-ai-engine
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "omnigo.name" . }}-ai-engine
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: ai-engine
          image: "{{ .Values.services.aiEngine.image }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8088"
            - name: REDIS_ADDR
              value: "{{ .Values.global.redis.addrs }}"
            - name: KAFKA_BROKERS
              value: "{{ .Values.global.kafka.brokers }}"
          ports:
            - containerPort: 8088
              name: http
          resources:
            {{- toYaml .Values.services.aiEngine.resources | nindent 12 }}
