{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "omnigo.fullname" . }}-redis
  labels:
    {{- include "omnigo.labels" . }}
spec:
  ports:
    - name: node-1
      port: 6379
      targetPort: 6379
    - name: node-2
      port: 6380
      targetPort: 6380
    - name: node-3
      port: 6381
      targetPort: 6381
  selector:
    app.kubernetes.io/name: {{ include "omnigo.name" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "omnigo.fullname" . }}-redis
  labels:
    {{- include "omnigo.labels" . }}
spec:
  serviceName: {{ include "omnigo.fullname" . }}-redis
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "omnigo.name" . }}-redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "omnigo.name" . }}-redis
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image }}"
          command: ["redis-server", "--port", "6379", "--cluster-enabled", "yes", "--cluster-config-file", "/tmp/nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes", "--bind", "0.0.0.0"]
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redisdata
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redisdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
{{- end }}
