apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omnigo.fullname" . }}-secrets
  labels:
    {{- include "omnigo.labels" . }}
type: Opaque
data:
  postgres-password: {{ .Values.global.postgres.password | b64enc | quote }}
  postgres-user: {{ .Values.global.postgres.user | b64enc | quote }}
  postgres-db: {{ .Values.global.postgres.db | b64enc | quote }}
  jwt-secret: {{ .Values.global.jwtSecret | b64enc | quote }}
  neo4j-password: {{ .Values.global.neo4j.password | b64enc | quote }}
  meilisearch-master-key: {{ .Values.global.meilisearch.masterKey | b64enc | quote }}
  db-writer-dsn: {{ printf "postgres://%s:%s@%s-postgres:%d/%s?sslmode=disable" .Values.global.postgres.user .Values.global.postgres.password (include "omnigo.fullname" .) (int .Values.global.postgres.port) .Values.global.postgres.db | b64enc | quote }}
  db-reader-dsn: {{ printf "postgres://%s:%s@%s-postgres:%d/%s?sslmode=disable" .Values.global.postgres.user .Values.global.postgres.password (include "omnigo.fullname" .) (int .Values.global.postgres.port) .Values.global.postgres.db | b64enc | quote }}
