{{- if .Values.tigerbeetle.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "omnigo.fullname" . }}-tigerbeetle
  labels:
    {{- include "omnigo.labels" . }}
spec:
  ports:
    - port: {{ .Values.tigerbeetle.port }}
      targetPort: 3000
  selector:
    app.kubernetes.io/name: {{ include "omnigo.name" . }}-tigerbeetle
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "omnigo.fullname" . }}-tigerbeetle
  labels:
    {{- include "omnigo.labels" . }}
spec:
  replicas: {{ .Values.tigerbeetle.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "omnigo.name" . }}-tigerbeetle
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "omnigo.name" . }}-tigerbeetle
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: tigerbeetle
          image: "{{ .Values.tigerbeetle.image }}"
          command: ["sh", "-c", "if [ ! -f /data/0_0.tigerbeetle ]; then ./tigerbeetle format --cluster=0 --replica=0 --replica-count=1 /data/0_0.tigerbeetle; fi && ./tigerbeetle start --addresses=0.0.0.0:3000 /data/0_0.tigerbeetle"]
          ports:
            - containerPort: 3000
              name: tigerbeetle
          volumeMounts:
            - name: tbdata
              mountPath: /data
      volumes:
        - name: tbdata
          emptyDir: {}
{{- end }}
