ALTER TABLE deliveries ADD COLUMN IF NOT EXISTS is_cod BOOLEAN DEFAULT false;
ALTER TABLE deliveries ADD COLUMN IF NOT EXISTS order_total NUMERIC(10,2) DEFAULT 0.0;
ALTER TABLE deliveries ADD COLUMN IF NOT EXISTS customer_phone VARCHAR(20) DEFAULT '';
